server:
  port: 8082
  servlet:
    contextPath: /boardgame
spring:
  datasource:
    password: Mrsimon260??root;):)
    url: jdbc:mysql://localhost:3306/boardgame?user=root
    driverClassName: com.mysql.cj.jdbc.Driver